namespace: microserviceD

public:
  - web

services:
  web:
    image: node:4
    ports:
      - "3000:3000"
    volumes:
      - ..:/microserviceD
    working_dir: /microserviceD
    command: [npm, start]

setup:
  - cd .. && npm install
